[package]
name = "coco"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.5.0"
color-eyre = "0.6.3"
serde = { version = "1.0.217", features = ["derive"] }
serde-lexpr = "0.1.3"
thiserror = "2.0.11"
